micronaut:
  application:
    name: home-budget
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:homeBudgetApplicationDefaultSecret}"'

mongodb:
  uri: ${MONGO_URI:`mongodb://localhost:27017/database`}

db:
  name: lab

jackson:
  serialization:
    writeDatesAsTimestamps: false
  property-naming-strategy: SNAKE_CASE